const state={user:window.APP_BOOT.user||null,themes:[],selectedThemeIds:new Set(),currentLobbyId:null,currentLobbyCode:null,lobbyPollTimer:null,isMobile:window.matchMedia('(max-width: 900px)').matches,banTargetThemeId:null,timer:null,timerValue:30};
const screens={home:homeScreen,themeBank:themeBankScreen,createLobby:createLobbyScreen,lobbyWaiting:lobbyWaitingScreen,joinLobby:joinLobbyScreen,playerLobby:playerLobbyScreen,hostGame:hostGameScreen,admin:adminScreen};
const els={authInfo,loginBtn,logoutBtn,adminBtn,desktopHome,mobileHome,themeSearch,themesList,themesCount,themeForm,themeStatus,themeFormInfo,lobbyThemeSearch,lobbyThemesList,lobbyCreateStatus,lobbyCodeText,lobbyPlayers,playerLobbyCode,playerWaitingInfo,playerScoreboard,buzzerBtn,playerBuzzerWrap,hostPlayersBoard,hostGameBoard,quizInfo,hostQuestionOverlay,hqTheme,hqPoints,hqQuestion,hqAnswerBox,hqAnswer,currentBuzzed,timerValue,loginOverlay,loginForm,registerForm,loginStatus,registerStatus,joinLobbyForm,joinStatus,bansList,banOverlay,banUserInfo,banDays,banStatus};
function switchScreen(name){Object.values(screens).forEach(s=>s.classList.remove('active'));screens[name].classList.add('active')}
function setStatus(node,text='',type=''){node.textContent=text;node.className='status'+(type?' '+type:'')}
function escapeHtml(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function shorten(t,m){const v=String(t||'');return v.length>m?v.slice(0,m-1)+'…':v}
async function api(action,payload={}){const r=await fetch('api.php?action='+encodeURIComponent(action),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!d.ok)throw new Error(d.error||'Ошибка');return d}
function renderAuth(){if(state.user){els.authInfo.textContent=`Вы вошли как ${state.user.username}${state.user.is_admin?' (админ)':''}`;loginBtn.classList.add('hidden');logoutBtn.classList.remove('hidden');adminBtn.classList.toggle('hidden',!state.user.is_admin);themeFormInfo.textContent=state.user.is_admin?'Администратор может создавать и удалять любые темы.':`Автор темы: ${state.user.username}`;}else{els.authInfo.textContent='Гость';loginBtn.classList.remove('hidden');logoutBtn.classList.add('hidden');adminBtn.classList.add('hidden');themeFormInfo.textContent='Для создания темы нужен вход в аккаунт'}if(state.isMobile){desktopHome.classList.add('hidden');mobileHome.classList.remove('hidden')}else{desktopHome.classList.remove('hidden');mobileHome.classList.add('hidden')}}
async function loadThemes(){const d=await api('list_themes');state.themes=d.themes||[];renderThemes();renderLobbyThemeSelect()}
function renderThemes(){const q=themeSearch.value.trim().toLowerCase();const filtered=state.themes.filter(t=>t.title.toLowerCase().includes(q));themesCount.textContent=`Всего тем: ${state.themes.length}`;themesList.innerHTML='';if(!filtered.length){themesList.innerHTML='<div class="muted">Темы не найдены.</div>';return}filtered.forEach(theme=>{const card=document.createElement('div');card.className='topic-card';card.innerHTML=`<div class="card-head" style="padding:0;border:0"><div><div style="font-size:20px;font-weight:900;">${escapeHtml(theme.title)}</div><div class="muted">Автор: ${escapeHtml(theme.owner_name)}</div></div><div class="row">${theme.can_delete?`<button class="btn danger" data-del="${theme.id}">Удалить</button>`:''}${theme.can_ban_owner?`<button class="btn secondary" data-ban="${theme.id}">Забанить автора</button>`:''}</div></div><div class="preview-grid"><div class="preview-item"><strong>100</strong>${escapeHtml(shorten(theme.q100,60))}</div><div class="preview-item"><strong>200</strong>${escapeHtml(shorten(theme.q200,60))}</div><div class="preview-item"><strong>300</strong>${escapeHtml(shorten(theme.q300,60))}</div><div class="preview-item"><strong>400</strong>${escapeHtml(shorten(theme.q400,60))}</div><div class="preview-item"><strong>500</strong>${escapeHtml(shorten(theme.q500,60))}</div></div>`;themesList.appendChild(card)});themesList.querySelectorAll('[data-del]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Удалить тему?'))return;try{await api('delete_theme',{theme_id:Number(b.dataset.del)});await loadThemes()}catch(e){alert(e.message)}}));themesList.querySelectorAll('[data-ban]').forEach(b=>b.addEventListener('click',()=>{state.banTargetThemeId=Number(b.dataset.ban);const theme=state.themes.find(t=>t.id==state.banTargetThemeId);banUserInfo.textContent=theme?`Пользователь: ${theme.owner_name}, тема: ${theme.title}`:'';banOverlay.classList.remove('hidden');setStatus(banStatus,'');banDays.value=''}))}
function renderLobbyThemeSelect(){const q=lobbyThemeSearch.value.trim().toLowerCase();const filtered=state.themes.filter(t=>t.title.toLowerCase().includes(q));lobbyThemesList.innerHTML='';if(!filtered.length){lobbyThemesList.innerHTML='<div class="muted">Темы не найдены.</div>';return}filtered.forEach(theme=>{const checked=state.selectedThemeIds.has(theme.id)?'checked':'';const card=document.createElement('div');card.className='topic-card';card.innerHTML=`<div class="card-head" style="padding:0;border:0"><label class="row" style="font-size:18px;font-weight:900;cursor:pointer;"><input type="checkbox" data-theme-check="${theme.id}" ${checked}/> ${escapeHtml(theme.title)}</label><div class="muted">Автор: ${escapeHtml(theme.owner_name)}</div></div>`;lobbyThemesList.appendChild(card)});lobbyThemesList.querySelectorAll('[data-theme-check]').forEach(box=>box.addEventListener('change',e=>{const id=Number(e.target.dataset.themeCheck);if(e.target.checked)state.selectedThemeIds.add(id);else state.selectedThemeIds.delete(id)}))}
themeForm.addEventListener('submit',async e=>{e.preventDefault();if(!state.user){setStatus(themeStatus,'Сначала войди в аккаунт.','error');return}const payload={title:theme_name.value.trim(),q100:q100.value.trim(),a100:a100.value.trim(),q200:q200.value.trim(),a200:a200.value.trim(),q300:q300.value.trim(),a300:a300.value.trim(),q400:q400.value.trim(),a400:a400.value.trim(),q500:q500.value.trim(),a500:a500.value.trim()};try{await api('create_theme',payload);themeForm.reset();setStatus(themeStatus,'Тема сохранена.','ok');await loadThemes()}catch(e2){setStatus(themeStatus,e2.message,'error')}})
async function createLobby(){try{const d=await api('create_lobby',{theme_ids:[...state.selectedThemeIds]});state.currentLobbyId=d.lobby_id;state.currentLobbyCode=d.code;lobbyCodeText.textContent=d.code;hostGameCode.textContent=d.code;switchScreen('lobbyWaiting');startLobbyPolling()}catch(e){setStatus(lobbyCreateStatus,e.message,'error')}}
function renderPlayers(container,members,buzzedId=null){container.innerHTML='';members.forEach(m=>{const card=document.createElement('div');card.className='player-card';card.innerHTML=`<div class="player-top"><div class="player-name">${escapeHtml(m.avatar)} ${escapeHtml(m.nickname)}</div><div class="pill">${buzzedId&&Number(buzzedId)===Number(m.id)?'Отвечает':'В игре'}</div></div><div class="player-score">${m.score}</div>`;container.appendChild(card)})}
function renderHostBoard(themes,used){const usedSet=new Set(used||[]);const points=[100,200,300,400,500];const cols=themes.length;hostGameBoard.innerHTML='';const head=document.createElement('div');head.className='board-head';head.style.gridTemplateColumns=`repeat(${cols}, minmax(140px,1fr))`;themes.forEach(theme=>{const cell=document.createElement('div');cell.className='cell header';cell.textContent=theme.title;head.appendChild(cell)});hostGameBoard.appendChild(head);points.forEach(point=>{const row=document.createElement('div');row.className='board-row';row.style.gridTemplateColumns=`repeat(${cols}, minmax(140px,1fr))`;themes.forEach(theme=>{const key=`${theme.id}_${point}`;const btn=document.createElement('button');btn.className='cell question'+(usedSet.has(key)?' used':'');btn.textContent=point;btn.disabled=usedSet.has(key);btn.addEventListener('click',async()=>{try{await api('open_question',{lobby_id:state.currentLobbyId,theme_id:theme.id,points:point});await fetchLobbyState()}catch(e){alert(e.message)}});row.appendChild(btn)});hostGameBoard.appendChild(row)})}
async function fetchLobbyState(){if(!state.currentLobbyId)return;const d=await api('get_lobby_state',{lobby_id:state.currentLobbyId});const {lobby,members,themes,used,current_question,buzzed}=d;if(lobbyWaitingScreen.classList.contains('active')){renderPlayers(lobbyPlayers,members);if(lobby.status==='playing')switchScreen('hostGame')}if(hostGameScreen.classList.contains('active')||lobby.status==='playing'){renderPlayers(hostPlayersBoard,members,buzzed?.id);renderHostBoard(themes,used);quizInfo.textContent=`Тем в игре: ${themes.length}`;if(current_question){hostGameCode.textContent=lobby.code;hqTheme.textContent=current_question.theme_title;hqPoints.textContent=`${current_question.points} очков`;hqQuestion.textContent=current_question.question;hqAnswer.textContent=current_question.answer;hqAnswerBox.classList.toggle('hidden',Number(lobby.answer_shown)!==1);currentBuzzed.textContent=buzzed?`${buzzed.avatar} ${buzzed.nickname}`:'Пока никто не нажал';hostQuestionOverlay.classList.remove('hidden')}else{hostQuestionOverlay.classList.add('hidden');stopTimer()}}if(playerLobbyScreen.classList.contains('active')){playerLobbyCode.textContent=lobby.code;renderPlayers(playerScoreboard,members,buzzed?.id);playerWaitingInfo.textContent=lobby.status==='playing'?(current_question?'Вопрос открыт. Жди или жми кнопку.':'Игра идёт. Ждём следующий вопрос.'):'Ожидание начала игры...';if(current_question&&Number(lobby.buzzer_open)===1){playerBuzzerWrap.classList.remove('hidden');buzzerBtn.disabled=false;buzzerBtn.classList.remove('grey');buzzerBtn.textContent='ЖМИ'}else if(current_question&&buzzed){playerBuzzerWrap.classList.remove('hidden');if(Number(d.my_member_id)===Number(buzzed.id)){buzzerBtn.disabled=true;buzzerBtn.textContent='ТЫ НАЖАЛ';buzzerBtn.classList.remove('grey')}else{buzzerBtn.disabled=true;buzzerBtn.classList.add('grey');buzzerBtn.textContent='КНОПКА ЗАБЛОКИРОВАНА'}}else{playerBuzzerWrap.classList.add('hidden');buzzerBtn.textContent='ЖМИ';buzzerBtn.classList.remove('grey');buzzerBtn.disabled=false}}}
function startLobbyPolling(){stopLobbyPolling();state.lobbyPollTimer=setInterval(()=>fetchLobbyState().catch(()=>{}),1500);fetchLobbyState().catch(()=>{})} function stopLobbyPolling(){if(state.lobbyPollTimer){clearInterval(state.lobbyPollTimer);state.lobbyPollTimer=null}}
joinLobbyForm.addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('join_lobby',{code:joinCode.value.trim(),nickname:joinNick.value.trim(),avatar:joinAvatar.value});state.currentLobbyId=d.lobby_id;state.currentLobbyCode=d.code;playerLobbyCode.textContent=d.code;switchScreen('playerLobby');startLobbyPolling();setStatus(joinStatus,'')}catch(e2){setStatus(joinStatus,e2.message,'error')}})
async function loginDo(username,password){const d=await api('login',{username,password});state.user=d.user;renderAuth();loginOverlay.classList.add('hidden')}
async function registerDo(username,password){const d=await api('register',{username,password});state.user=d.user;renderAuth();loginOverlay.classList.add('hidden')}
async function logoutDo(){await api('logout');state.user=null;renderAuth()}
function showLoginOverlay(tab='login'){loginOverlay.classList.remove('hidden');loginForm.classList.toggle('hidden',tab!=='login');registerForm.classList.toggle('hidden',tab!=='register');setStatus(loginStatus,'');setStatus(registerStatus,'')}
function audioCtx(){const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return null;if(!window.__audioCtx)window.__audioCtx=new Ctx();return window.__audioCtx} function beep(freq=440,duration=.1,type='sine',volume=.04){const ctx=audioCtx();if(!ctx)return;const osc=ctx.createOscillator();const gain=ctx.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.value=volume;osc.connect(gain);gain.connect(ctx.destination);osc.start();gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+duration);osc.stop(ctx.currentTime+duration)} function playStartSound(){beep(660,.08,'square',.04);setTimeout(()=>beep(880,.08,'square',.04),90)} function playTickSound(){beep(1100,.05,'square',.03)} function playTimeoutSound(){beep(240,.18,'sawtooth',.05);setTimeout(()=>beep(180,.22,'sawtooth',.05),160)}
function startTimer(){stopTimer();state.timerValue=30;timerValue.textContent='30';timerValue.classList.remove('danger');playStartSound();state.timer=setInterval(()=>{state.timerValue-=1;timerValue.textContent=String(state.timerValue);if(state.timerValue<=5){timerValue.classList.add('danger');playTickSound()}if(state.timerValue<=0){stopTimer();playTimeoutSound()}},1000)} function stopTimer(){if(state.timer)clearInterval(state.timer);state.timer=null}
async function loadBans(){try{const d=await api('list_bans');bansList.innerHTML='';if(!d.bans.length){bansList.innerHTML='<div class="muted">Активных банов нет.</div>';return}d.bans.forEach(ban=>{const card=document.createElement('div');card.className='topic-card';card.innerHTML=`<div style="font-size:18px;font-weight:900;">${escapeHtml(ban.username)}</div><div class="muted">Тема: ${escapeHtml(ban.reason_theme_title||'—')}</div><div class="muted">${ban.is_forever==1?'Забанен навсегда':'До '+ban.banned_until}</div><div class="row"><button class="btn gold" data-unban="${ban.id}">Разбан</button></div>`;bansList.appendChild(card)});bansList.querySelectorAll('[data-unban]').forEach(btn=>btn.addEventListener('click',async()=>{try{await api('unban_user',{ban_id:Number(btn.dataset.unban)});await loadBans();await loadThemes()}catch(e){alert(e.message)}}))}catch(e){bansList.innerHTML=`<div class="muted">${escapeHtml(e.message)}</div>`}}
homeBtn.addEventListener('click',()=>switchScreen('home'));loginBtn.addEventListener('click',()=>showLoginOverlay('login'));logoutBtn.addEventListener('click',()=>logoutDo().catch(()=>{}));adminBtn.addEventListener('click',async()=>{switchScreen('admin');await loadBans()})
goThemeBankBtn.addEventListener('click',async()=>{switchScreen('themeBank');await loadThemes()});goCreateLobbyBtn.addEventListener('click',async()=>{if(!state.user){showLoginOverlay('login');return}switchScreen('createLobby');await loadThemes()});goJoinLobbyBtn.addEventListener('click',()=>switchScreen('joinLobby'));goJoinLobbyBtnMobile.addEventListener('click',()=>switchScreen('joinLobby'));document.querySelectorAll('.back-home').forEach(btn=>btn.addEventListener('click',()=>switchScreen('home')))
themeSearch.addEventListener('input',renderThemes);lobbyThemeSearch.addEventListener('input',renderLobbyThemeSelect);refreshThemesBtn.addEventListener('click',loadThemes);createLobbyConfirmBtn.addEventListener('click',createLobby);startGameBtn.addEventListener('click',async()=>{try{await api('start_game',{lobby_id:state.currentLobbyId});switchScreen('hostGame');await fetchLobbyState()}catch(e){alert(e.message)}})
buzzerBtn.addEventListener('click',async()=>{try{await api('buzz',{lobby_id:state.currentLobbyId});buzzerBtn.disabled=true;buzzerBtn.textContent='ТЫ НАЖАЛ'}catch(e){}});showAnswerBtn.addEventListener('click',async()=>{try{await api('show_answer',{lobby_id:state.currentLobbyId});await fetchLobbyState()}catch(e){alert(e.message)}});correctBtn.addEventListener('click',async()=>{try{await api('mark_correct',{lobby_id:state.currentLobbyId});await fetchLobbyState()}catch(e){alert(e.message)}});wrongBtn.addEventListener('click',async()=>{try{await api('mark_wrong',{lobby_id:state.currentLobbyId});await fetchLobbyState()}catch(e){alert(e.message)}});closeQuestionBtn.addEventListener('click',async()=>{try{await api('close_question',{lobby_id:state.currentLobbyId});await fetchLobbyState()}catch(e){alert(e.message)}})
backToLobbyBtn.addEventListener('click',()=>switchScreen('lobbyWaiting'));timerStartBtn.addEventListener('click',startTimer);timerStopBtn.addEventListener('click',stopTimer)
showLoginTab.addEventListener('click',()=>showLoginOverlay('login'));showRegisterTab.addEventListener('click',()=>showLoginOverlay('register'));closeLoginOverlayBtn.addEventListener('click',()=>loginOverlay.classList.add('hidden'));closeLoginOverlayBtn2.addEventListener('click',()=>loginOverlay.classList.add('hidden'))
loginForm.addEventListener('submit',async e=>{e.preventDefault();try{await loginDo(loginName.value.trim(),loginPass.value)}catch(e2){setStatus(loginStatus,e2.message,'error')}});registerForm.addEventListener('submit',async e=>{e.preventDefault();try{await registerDo(regName.value.trim(),regPass.value)}catch(e2){setStatus(registerStatus,e2.message,'error')}})
refreshAdminBtn.addEventListener('click',loadBans);closeBanOverlayBtn.addEventListener('click',()=>banOverlay.classList.add('hidden'));applyBanBtn.addEventListener('click',async()=>{try{await api('ban_user',{theme_id:state.banTargetThemeId,days:Number(banDays.value||0),forever:0});banOverlay.classList.add('hidden');await loadThemes();await loadBans()}catch(e){setStatus(banStatus,e.message,'error')}});applyForeverBanBtn.addEventListener('click',async()=>{try{await api('ban_user',{theme_id:state.banTargetThemeId,forever:1});banOverlay.classList.add('hidden');await loadThemes();await loadBans()}catch(e){setStatus(banStatus,e.message,'error')}})
window.addEventListener('beforeunload',stopLobbyPolling);(async function(){renderAuth();await loadThemes();switchScreen('home')})()
